### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by franktopel** [lpcruz/unsplash_scrape#1]
Traceback (most recent call last):
  File "unsplash-scrape.py", line 2, in <module>
    import requests
ImportError: No module named requests

**Comment by lpcruz** [comment]
You'll need the Requests module, which you can install with pip or sudo easy_install. Simply run either in terminal:

### install with pip

```
$ pip install requests
```

### install with sudo easy_install

```
$ sudo easy_install requests
```

**Comment by lpcruz** [comment]
You'll also need beautifulsoup4 to successfully run it:

### install with pip

```
$ pip install beautifulsoup4
```

### install with sudo easy_install

```
$ sudo easy_install beautifulsoup4
```

**Comment by lpcruz** [comment]
@franktopel let me know if you're still having issues.

**Comment by franktopel** [comment]
Works now, thanks for the help. I even had to install pip first. First time I ever got in touch with Python... The issue that remains is that your script downloads only very few images (<20). I assume that is because unsplash.com loads the images only on scrolling via ajax?

**Comment by lpcruz** [comment]
@franktopel Great - I'm glad you got it to work. Functional Python scripts will often require modules so you'll most likely have to download specific packages based on a script. That said, I'm aware of the < ~20 image download and have marked it as a known-issue, 

It does appear that unsplash uses ajax to load the image on scroll - most likely to avoid slow load time. I'll be working on improving the way my script runs on the page. Specifically, I'll most likely need to use a webdriver such as Selenium to navigate through the page and emulate the action of scrolling. Will need to test that on my end. 

Thanks for taking the time to test out this script - it was simply a small project. If you have any other critiques, thoughts, or issues, please let me know.

**Comment by lpcruz** [comment]
@franktopel refactored the script. I would run a git pull to get the latest updates if you still have the repo. Otherwise, feel free to download this repo and give the script a shot. Let me know if you have any problems. Thanks!
